"""users update

Revision ID: 0259807f74ac
Revises: 925b1d08ff65
Create Date: 2023-09-01 03:19:12.427233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0259807f74ac'
down_revision: Union[str, None] = '925b1d08ff65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'referrer_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'referrer_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
