"""Question.from_message_id

Revision ID: 1a0902574080
Revises: 2f5248f579da
Create Date: 2023-09-06 04:50:05.390928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a0902574080'
down_revision: Union[str, None] = '2f5248f579da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('from_message_id', sa.BIGINT(), nullable=False))
    op.add_column('questions', sa.Column('to_message_id', sa.BIGINT(), nullable=False))
    op.drop_constraint('questions_message_id_key', 'questions', type_='unique')
    op.create_unique_constraint(None, 'questions', ['from_message_id'])
    op.create_unique_constraint(None, 'questions', ['to_message_id'])
    op.drop_column('questions', 'message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('message_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_constraint(None, 'questions', type_='unique')
    op.create_unique_constraint('questions_message_id_key', 'questions', ['message_id'])
    op.drop_column('questions', 'to_message_id')
    op.drop_column('questions', 'from_message_id')
    # ### end Alembic commands ###
