"""questions

Revision ID: 2d7689bc6ac9
Revises: f95f66991f2f
Create Date: 2023-09-01 01:58:21.730008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d7689bc6ac9'
down_revision: Union[str, None] = 'f95f66991f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('question_from', sa.BIGINT(), nullable=False),
    sa.Column('question_to', sa.BIGINT(), nullable=False),
    sa.Column('text', sa.String(length=4096), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_from'], ['users.user_id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['question_to'], ['users.user_id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('referrer_id', sa.BIGINT(), nullable=False))
    op.create_foreign_key(None, 'users', 'users', ['referrer_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referrer_id')
    op.drop_table('questions')
    # ### end Alembic commands ###
