"""Question.message_id

Revision ID: 2f5248f579da
Revises: 0259807f74ac
Create Date: 2023-09-06 03:52:27.908524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f5248f579da'
down_revision: Union[str, None] = '0259807f74ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('message_id', sa.BIGINT(), nullable=False))
    op.create_unique_constraint(None, 'questions', ['message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_column('questions', 'message_id')
    # ### end Alembic commands ###
