"""update

Revision ID: 925b1d08ff65
Revises: 2d7689bc6ac9
Create Date: 2023-09-01 02:58:56.081025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '925b1d08ff65'
down_revision: Union[str, None] = '2d7689bc6ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.drop_column('questions', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.drop_column('questions', 'question_id')
    # ### end Alembic commands ###
